import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  filter10, filter11, filter12, filter13, filter14, filter15, filter16, filter17,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: 1001,
    img: filter10,
    productName: "СРФ8 СРФ 8",
    price: "35.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: filter11,
    productName: "СРФ22 СРФ 8",
    price: "180.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: filter12,
    productName: "СРФ22 СРФ 8",
    price: "25.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: filter13,
    productName: "СРФ2 СРФ 8",
    price: "220.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: filter10,
    productName: "СРФ8 СРФ 8",
    price: "35.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: filter11,
    productName: "СРФ22 СРФ 8",
    price: "180.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: filter12,
    productName: "СРФ22 СРФ 8",
    price: "25.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: filter13,
    productName: "СРФ2 СРФ 8",
    price: "220.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: filter14,
    productName: "ФРИП-15",
    price: "35.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: filter14,
    productName: "ФРИП-30",
    price: "180.00",
    color: "рукавный фильтр",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: filter14,
    productName: "ФРИП-60",
    price: "25.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: filter14,
    productName: "ФРИП-90",
    price: "250.00",
    color: "рукавный фильтр",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: filter14,
    productName: "ФРИП-180",
    price: "250.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: filter14,
    productName: "ФРИП-270",
    price: "250.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: filter14,
    productName: "ФРИП-360",
    price: "250.00",
    color: "рукавный фильтр",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: filter14,
    productName: "ФРИП-540",
    price: "250.00",
    color: "рукавный фильтр",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: filter15,
    productName: "Фильтр ФРКИ-90",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1014,
    img: filter15,
    productName: "Фильтр ФРКИ-30",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: filter15,
    productName: "Фильтр ФРКИ-60",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: filter15,
    productName: "Фильтр ФРКИ-120",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: filter15,
    productName: "Фильтр ФРКИ-180",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: filter15,
    productName: "Фильтр ФРКИ-360",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: filter15,
    productName: "Фильтр ФРКИ-450",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: filter16,
    productName: "Фильтр ФРИ-6",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: filter16,
    productName: "Фильтр ФРИ-9",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: filter17,
    productName: "Фильтр ФРИ-12",
    price: "60.00",
    color: "площадью фильтрующей поверхности 90 м²",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  }
];
// =================== PaginationItems End here =================
